name: Continuous Deployment

on:
  pull_request:
    branches:
      - dev
    types:
      - closed
  workflow_dispatch:

jobs:
  if-merged:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: If merged
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ] && [ "${{ github.event.action }}" == "closed" ] && [ "${{ github.event.pull_request.merged }}" == "true" ]; then
            echo "Merged"
          else
            echo "Not merged"
        shell: bash
  test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        shell: bash

      - name: Run tests
        run: |
          pytest
        shell: bash
  
  build:
    name: Build Docker Image
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: mrnothing01/fast_api_git_action_ci_cd
      
      - name: Print Meta Info
        run:
          echo "Meta ------------ ${{ steps.meta.outputs }}"
          echo "The tags are ${{ steps.meta.outputs.tags }}"
          echo "The labels are ${{ steps.meta.outputs.labels }}"
        shell: bash
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

    
