name: FastAPI workflow for Testing, Scanning, Testing and Build

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
  workflow_dispatch:

jobs:
  code-quantity:
    name: Check Code Quantity
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: poetry

      - name: Install dependencies
        run: poetry install

      - name: Check code quantity
        run: poetry run radon cc --total-average --show-complexity --show-closures


